<?php


namespace App\Repositories;

use App\Models\BlogPost as Model;

class BlogPostRepository extends CoreRepository
{

    protected function getModelClass()
    {
        return Model::class;
    }

    protected function startConditions()
    {
        return clone $this->model;// TODO: Change the autogenerated stub
    }

    public function getAllWithPaginate($perPage = null)
    {
        $columns = [
            'id',
            'title',
            'slug',
            'is_published',
            'published_at',
            'user_id',
            'category_id'
        ];

        $result = $this
            ->startConditions()
            ->select($columns)
            ->orderBy('id','DESC')
            //->with(['category','user'])
            ->with([
                //первый вариант
//                'category' => function($query){
//                    $query->select(['id','title']);
//                },
                // Второй короткий вариант
                'category:id,title',
                'user:id,name',
            ])
            ->paginate($perPage);
        //dd($result);
        return $result;
    }

    /**
     * @param $id
     * @return Model
     */
    public function getEdit($id){
        return $this->startConditions()->find($id);
    }
}
